<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NurturedChoice.Application\NurturedChoice.Application.csproj" />
    <ProjectReference Include="..\NurturedChoice.Domain\NurturedChoice.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.1" />

    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />

    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\migrations\*.sql" Link="Migrations\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
